


# version: "3.10"
# services:
#   db:
#       image: postgres
#       ports:
#         - 5432:5432
#       volumes:
#         - ./data/db:/var/lib/postgresql/data 777
#       environment:
#         - POSTGRES_DB=pavshop
#         - POSTGRES_USER=Turkay
#         - POSTGRES_PASSWORD=Password19
#       container_name: postgres_db

version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'products_db'
    # volumes:
    #   - ./mydb:/var/lib/mysql

  adminer:
    image: adminer:4.7.8
    restart: always
    ports:
      - 8080:8080